### ISSUE TITLE
撈到不屬於該開課單位的課

### ISSUE THREAD

**Issue by x3388638** [NCNU-OpenSource/ncnu-course-search-engine#6]
https://ncnu-course.herokuapp.com/search?faculty=%E4%B8%8D%E6%8C%87%E5%AE%9A&department=%E8%B3%87%E7%AE%A1%E7%B3%BB&credit=%E4%B8%8D%E6%8C%87%E5%AE%9A&division=%E4%B8%8D%E6%8C%87%E5%AE%9A&location=%E4%B8%8D%E6%8C%87%E5%AE%9A&teacher=&classtime=&course_id=

EX:
Excel 原理與進階應用 & 台股投資法則 開課單位應該是「通識」

**Comment by yiyu0x** [comment]
回報給計中 是學校open data的問題 
感謝回報 已修復
